### PR TITLE
Protocol v2

### PR DESCRIPTION
**Pull request by dsferruzza**
This requires:
- [ ] implementing protocol v2 on the firmware side
- [ ] testing that communication is working

### CODE REVIEW

**Review by valeriansaliou — CHANGES_REQUESTED** [review]
Looks good, except for the telemetry protocol version mismatch. Would there be a way for the telemetry library to expose either a method or send an event in the TX channel so that the UI can be notified whenever there is a protocol mismatch? That way I do not need hardcoding the protocol version in the UI to compare it w/ the received packet.

**Comment by valeriansaliou** [comment]
I guess we could merge and see how it goes after I update it in the UI and implement Protocol V2?

**Comment by dsferruzza** [comment]
> Looks good, except for the telemetry protocol version mismatch. Would there be a way for the telemetry library to expose either a method or send an event in the TX channel so that the UI can be notified whenever there is a protocol mismatch? That way I do not need hardcoding the protocol version in the UI to compare it w/ the received packet.

What would be a protocol mismatch? Like when receiving data in an outdated protocol?

---

> I guess we could merge and see how it goes after I update it in the UI and implement Protocol V2?

I found a bug in the firmware implementation which was almost ready. So I guess it will be ready very soon. But if you need this merged before we can do it.

**Comment by valeriansaliou** [comment]
@dsferruzza a protocol mismatch would be receiving a message for the wrong protocol. I’d say any message matching the wrong protocol.

**Comment by dsferruzza** [comment]
But how do you define "the wrong protocol"? "Not the latest"? Or a future protocol version that the software would not support?

**Comment by valeriansaliou** [comment]
I'd say an unsupported protocol, so if we consider we ensure backwards-compatibility in the telemetry library, then a protocol greater than the maximum supported protocol.

**Comment by valeriansaliou** [comment]
Can we merge this now anyway? I'll need this by tomorrow to implement this as soon as possible.

**Pull request merged**
