### PR TITLE
Add optional measured volume in MachineStateSnapshot

### PR DESCRIPTION
**Pull request by dsferruzza**
This is linked to makers-for-life/makair-firmware#19

### CODE REVIEW

**Comment by jtanguy** [comment]
Shouldn't we also impact the `telemetry.proto` definition ?

**Comment by dsferruzza** [comment]
Indeed but probably later. The point here is to be able to check if makers-for-life/makair-firmware#19 works.

**Comment by hbs** [comment]
Not only telemetry.proto, the Warp 10 MakAir WarpScript Extension will also have to change and so will the warpscript macros which handle the encoding/decoding of frames into/from a protobuf message

**Comment by jtanguy** [comment]
We could rename the field `previous_tidal_volume`, as it would be consistent with the other field names.

**Comment by dsferruzza** [comment]
This will indeed require adaptations on several other systems but this won't be the only change to the telemetry protocol: I might land CRC and few more messages very soon (we need to do bi-directional communication so that the RPi can push settings updates).

**Pull request merged**
